### ISSUE TITLE
to-do list (mainly for text analysis)

### ISSUE THREAD

**Issue by jokergoo** [jokergoo/simplifyEnrichment#61]
- [ ] n-gram, (e.g. cell cycle)
- [ ] words (or abbreviations) with two letters, or to distinguish abbreviations that are the same as normal words, but all in upper case.
- [ ] "enrichment" of words (using all gene descriptions/GO definitions as background, maybe more sources)
- [ ] stemming of words
